"""Constantes globais do jogo — eliminam números mágicos."""

# Dimensões base do mapa
BASE_MAP_HEIGHT = 12
BASE_MAP_WIDTH = 25

# Incrementos por nível de masmorra
MAP_HEIGHT_INCREMENT_PER_5_LEVELS = 2
MAP_WIDTH_INCREMENT_PER_5_LEVELS = 4

# Configuração de paredes (geração de mapa)
MIN_WALL_PERCENT = 0.05
MAX_WALL_PERCENT = 0.20
WALL_PERCENT_PER_LEVEL = 0.01
MAX_WALL_PERCENT_CAP = 0.15  # Limite máximo de paredes por nível

# Intervalos de tempo (UX)
SLEEP_AFTER_SAVE = 1.5
SLEEP_SHORT_PAUSE = 1.0
SLEEP_MENU_REFRESH = 1.5
SLEEP_GAME_OVER = 2.0

# --- Estatísticas de Monstros ---
MONSTER_BASE_HP = 70
MONSTER_HP_SCALING_PER_LEVEL = 20
MONSTER_BASE_STRENGTH = 25
MONSTER_STRENGTH_SCALING_PER_LEVEL = 15
MONSTER_BASE_DEFENSE = 20
MONSTER_DEFENSE_SCALING_PER_LEVEL = 8
MONSTER_BASE_MAGIC = 40
MONSTER_MAGIC_SCALING_PER_LEVEL = 12

# --- Sistema de XP ---
XP_INITIAL_COST = 3000
XP_GROWTH_PER_LEVEL = 750
MONSTER_BASE_XP_REWARD = 50
MONSTER_XP_SCALING_PER_LEVEL = 20

# --- Mini-Bosses ---
MINI_BOSS_LEVEL_BONUS = 2
MINI_BOSS_BASE_HP = 150
MINI_BOSS_HP_SCALING_PER_LEVEL = 40
MINI_BOSS_BASE_STRENGTH = 80
MINI_BOSS_STRENGTH_SCALING_PER_LEVEL = 30
MINI_BOSS_BASE_DEFENSE = 45
MINI_BOSS_DEFENSE_SCALING_PER_LEVEL = 10
MINI_BOSS_BASE_MAGIC = 75
MINI_BOSS_MAGIC_SCALING_PER_LEVEL = 18
MINI_BOSS_BASE_XP_REWARD = 120
MINI_BOSS_XP_SCALING_PER_LEVEL = 25
