"""Lote Mage: 26 cartas novas, para fechar 40.

Identidade: Magia, pico, MP como recurso real, buffs e debuffs, risco/recompensa,
controle arcano. O Mago paga adiantado por tudo o que faz — e é essa conta que o
diferencia do Guerreiro, que paga com o corpo, e do Ladino, que paga com o timing.
"""

from skill_forge import Carta as C  # noqa: N817 — `C` mantém 150 cartas legíveis

CARTAS = [
    # ---------------- Common (13) ----------------
    C(
        id="lasca_de_gelo",
        name="Lasca de Gelo",
        cls="Mage",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Um estilhaço rápido que também rouba o passo de quem foi atingido.",
        esc="mg",
        bud=220,
        cond="target_healthy",
        bonus=12,
        sec=("slowed", 45, 3),
        cd=2,
        mp=5.5,
    ),
    C(
        id="fagulha_teimosa",
        name="Fagulha Teimosa",
        cls="Mage",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Barata e precisa: estala na altura dos olhos e o inimigo perde a mira.",
        esc="mg",
        bud=165,
        cond="target_wounded",
        bonus=18,
        sec=("fear", 35, 2),
        acc=10,
        cd=1,
        mp=4.0,
    ),
    C(
        id="marca_ardente",
        name="Marca Ardente",
        cls="Mage",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Uma runa queimada na pele que continua queimando depois.",
        esc="mg",
        bud=169,
        cond="target_wounded",
        bonus=20,
        sec=("poison", 55, 4),
        cd=2,
        mp=7.0,
    ),
    C(
        id="pulso_de_forca",
        name="Pulso de Força",
        cls="Mage",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Magia sem elegância: empurra tudo o que estiver na frente do cajado.",
        esc="mg",
        bud=175,
        cond="target_afflicted",
        bonus=22,
        acc=-5,
        req={"hand_type": "staff"},
        sec=("slowed", 50, 3),
        cd=2,
        mp=7.0,
    ),
    C(
        id="foco_do_estudante",
        name="Foco do Estudante",
        cls="Mage",
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Fecha os olhos e organiza o que sabe.",
        ev=30,
        stat="mg",
        dur=3,
        cd=2,
        mp=6.5,
    ),
    C(
        id="veias_de_eter",
        name="Veias de Éter",
        cls="Mage",
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="O éter volta a circular sozinho.",
        ev=12,
        stat="mana_regen",
        dur=4,
        cd=3,
        mp=5.0,
    ),
    C(
        id="reserva_profunda",
        name="Reserva Profunda",
        cls="Mage",
        rar="Common",
        lvl=6,
        tipo="buff",
        desc="Abre uma segunda gaveta de mana que ele guardava para depois.",
        ev=30,
        stat="mp",
        dur=4,
        cd=4,
        mp=5.5,
    ),
    C(
        id="palavra_de_torpor",
        name="Palavra de Torpor",
        cls="Mage",
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Uma sílaba só, dita devagar, e o corpo do outro esquece a pressa.",
        ev="slowed",
        dur=3,
        chance=75,
        sec=("clouded", 50, 3),
        cd=2,
        mp=5.5,
    ),
    C(
        id="dissonancia",
        name="Dissonância",
        cls="Mage",
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Desafina a magia alheia até ela não valer o gesto.",
        ev="hexed",
        dur=3,
        chance=75,
        sec=("clouded", 55, 3),
        cd=3,
        mp=6.0,
    ),
    C(
        id="pele_de_quartzo",
        name="Pele de Quartzo",
        cls="Mage",
        rar="Common",
        lvl=3,
        tipo="damage_reduction",
        desc="A pele endurece em placas translúcidas por um instante.",
        ev=22,
        dur=2,
        cd=3,
        mp=6.5,
    ),
    C(
        id="passo_borrado",
        name="Passo Borrado",
        cls="Mage",
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="O contorno do corpo atrasa meio segundo em relação a ele.",
        ev=28,
        stat="evasion",
        dur=3,
        cd=4,
        mp=7.5,
    ),
    C(
        id="mao_firme",
        name="Mão Firme",
        cls="Mage",
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="Cada gesto do encantamento sai no lugar exato.",
        ev=16,
        stat="crit_chance",
        dur=3,
        req={"hand_type": "staff"},
        cd=3,
        mp=7.0,
    ),
    C(
        id="lancar_pedra",
        name="Lançar Pedra",
        cls="Mage",
        rar="Common",
        lvl=9,
        tipo="damage",
        desc="Quando a mana acaba, sobra o que estiver no chão — e um empurrão arcano.",
        esc="mg",
        bud=171,
        cond="caster_wounded",
        bonus=25,
        sec=("stun", 18, 1),
        req={"hand_type": "staff"},
        cd=1,
        mp=3.5,
    ),
    # ---------------- Rare (8) ----------------
    C(
        id="lente_de_obsidiana",
        name="Lente de Obsidiana",
        cls="Mage",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="Concentra o feitiço num ponto do tamanho de uma moeda.",
        esc="mg",
        bud=225,
        cond="target_healthy",
        bonus=25,
        acc=15,
        req={"hand_type": "staff"},
        sec=("vulnerable", 55, 3),
        cd=3,
        mp=9.5,
    ),
    C(
        id="maldicao_de_cinzas",
        name="Maldição de Cinzas",
        cls="Mage",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="O feitiço não mata: ele começa a desfazer o alvo, e tem paciência.",
        esc="mg",
        bud=205,
        cond="target_afflicted",
        bonus=30,
        sec=("poison", 70, 5),
        cd=3,
        mp=9.0,
    ),
    C(
        id="troca_de_sangue",
        name="Troca de Sangue",
        cls="Mage",
        rar="Rare",
        lvl=12,
        tipo="damage",
        desc="Paga o feitiço com o que corre nas veias em vez do que corre no cajado.",
        esc="mg.7+hp.3",
        bud=240,
        cond="caster_wounded",
        bonus=35,
        sec=("frailty", 55, 3),
        cd=3,
        mp=6.0,
    ),
    C(
        id="grilhoes_de_gelo",
        name="Grilhões de Gelo",
        cls="Mage",
        rar="Rare",
        lvl=12,
        tipo="status",
        desc="O chão sobe pelas pernas do alvo e endurece.",
        ev="frozen",
        dur=2,
        chance=65,
        sec=("vulnerable", 60, 3),
        cd=4,
        mp=10.0,
    ),
    C(
        id="sanguessuga_arcana",
        name="Sanguessuga Arcana",
        cls="Mage",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Cada feitiço que conecta devolve um pouco do que custou.",
        ev=20,
        stat="life_steal",
        dur=3,
        cd=4,
        mp=10.5,
    ),
    C(
        id="clarividencia",
        name="Clarividência",
        cls="Mage",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Vê o golpe do inimigo um instante antes de ele decidir dá-lo.",
        ev=22,
        stat="ag",
        dur=3,
        req={"hand_type": "staff"},
        cd=4,
        mp=9.0,
    ),
    C(
        id="egide_de_runas",
        name="Égide de Runas",
        cls="Mage",
        rar="Rare",
        lvl=9,
        tipo="damage_reduction",
        desc="Seis runas giram devagar em volta do cajado e absorvem o que chega.",
        ev=35,
        dur=3,
        req={"hand_type": "staff"},
        cd=4,
        mp=11.0,
    ),
    C(
        id="palavra_de_pavor",
        name="Palavra de Pavor",
        cls="Mage",
        rar="Rare",
        lvl=9,
        tipo="status",
        desc="Diz o nome verdadeiro da coisa em voz alta e ela hesita.",
        ev="fear",
        dur=3,
        chance=75,
        sec=("frailty", 55, 3),
        cd=3,
        mp=8.0,
    ),
    # ---------------- Epic (5) ----------------
    C(
        id="prisma_de_devastacao",
        name="Prisma de Devastação",
        cls="Mage",
        rar="Epic",
        lvl=12,
        tipo="damage",
        desc="Um prisma se abre no ar e devolve o feitiço multiplicado por sete faces.",
        esc="mg",
        bud=310,
        cond="target_afflicted",
        bonus=45,
        sec=("vulnerable", 70, 3),
        acc=-10,
        req={"hand_type": "staff"},
        cd=4,
        mp=13.5,
    ),
    C(
        id="dividendo_de_mana",
        name="Dividendo de Mana",
        cls="Mage",
        rar="Epic",
        lvl=18,
        tipo="damage",
        desc="Converte a reserva inteira em uma única cobrança, e o troco é o estrago.",
        esc="mp",
        bud=350,
        cond="target_afflicted",
        bonus=40,
        sec=("mana_burn", 60, 2),
        cd=4,
        mp=16.0,
    ),
    C(
        id="hora_parada",
        name="Hora Parada",
        cls="Mage",
        rar="Epic",
        lvl=15,
        tipo="status",
        desc="O alvo continua no mesmo segundo enquanto o resto do mundo anda.",
        ev="sleep",
        dur=3,
        chance=65,
        sec=("hexed", 70, 3),
        cd=5,
        mp=14.0,
    ),
    C(
        id="pacto_do_vazio",
        name="Pacto do Vazio",
        cls="Mage",
        rar="Epic",
        lvl=15,
        tipo="buff",
        desc="Entrega parte do que é, e o que volta não sai pela metade.",
        ev=70,
        stat="crit_damage",
        dur=4,
        cd=5,
        mp=15.0,
    ),
    C(
        id="cerco_de_espelhos",
        name="Cerco de Espelhos",
        cls="Mage",
        rar="Epic",
        lvl=12,
        tipo="status",
        desc="Doze reflexos dele em volta do inimigo, e um só é real.",
        ev="fear",
        dur=3,
        chance=85,
        sec=("slowed", 70, 3),
        cd=5,
        mp=13.0,
    ),
]
