"""Lotes de monstro: 31 cartas novas, para fechar 54.

Mesma gramática do herói, catálogo diferente. O monstro não é "Guerreiro só que
vermelho": o que ele faz vem do ARQUÉTIPO, e o arquétipo existe para o jogador
poder aprender a lê-lo. Quando aparece um Controlador, a lição é "guarde o
turno"; quando aparece um Tanque, é "isto vai demorar".

Por isso as cartas novas de dano declaram condição situacional: um Brutamontes
que bate mais forte em quem já está ferido é legível, e legibilidade é o que
transforma um encontro em decisão em vez de rolagem.

Custo em mana ABSOLUTA, como as cartas de monstro que já existiam.
"""

from skill_forge import Carta as C  # noqa: N817 — `C` mantém 150 cartas legíveis

# --- Lote A: trash, bruiser, tank, glass_cannon (14) -----------------------

LOTE_A = [
    # trash (+3) — simples. Um bicho de andar raso não precisa de plano.
    C(
        id="mob_mordida_suja",
        name="Mordida Suja",
        papel="trash",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Dentes que não foram feitos para isso, e ainda assim funcionam.",
        esc="st",
        bud=115,
        cond="target_wounded",
        bonus=15,
        sec=("bleed", 30, 2),
        cd=2,
        mp=8,
    ),
    C(
        id="mob_guincho",
        name="Guincho",
        papel="trash",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Um som agudo e curto que atrapalha mais do que assusta.",
        ev="slowed",
        dur=2,
        chance=55,
        cd=3,
        mp=10,
    ),
    C(
        id="mob_encolher",
        name="Encolher",
        papel="trash",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage_reduction",
        desc="Se enrola no chão e espera o golpe passar por cima.",
        ev=18,
        dur=2,
        cd=4,
        mp=12,
    ),
    # bruiser (+4) — pressão física, sem sutileza e sem pausa.
    C(
        id="mob_cabecada",
        name="Cabeçada",
        papel="bruiser",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Testa contra nariz. Ganha quem tiver o crânio mais grosso.",
        esc="st",
        bud=150,
        cond="target_healthy",
        bonus=20,
        sec=("stun", 25, 1),
        acc=-10,
        cd=3,
        mp=18,
    ),
    C(
        id="mob_urro_de_caca",
        name="Urro de Caça",
        papel="bruiser",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Anuncia que escolheu um alvo, e o alvo sente o braço pesar.",
        ev="weakened",
        dur=3,
        chance=70,
        cd=4,
        mp=15,
    ),
    C(
        id="mob_couro_de_batalha",
        name="Couro de Batalha",
        papel="bruiser",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage_reduction",
        desc="Cicatriz sobre cicatriz até virar armadura.",
        ev=25,
        dur=3,
        cd=5,
        mp=20,
    ),
    C(
        id="mob_sangue_quente",
        name="Sangue Quente",
        papel="bruiser",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="buff",
        desc="Quanto mais tempo o combate dura, mais fundo ele acerta.",
        ev=20,
        stat="crit_chance",
        dur=4,
        cd=5,
        mp=18,
    ),
    # tank (+3) — defesa, controle e atrito. Ele ganha pelo relógio.
    C(
        id="mob_agarrao",
        name="Agarrão",
        papel="tank",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Fecha a mão no braço do herói e o combate passa a ser no ritmo dele.",
        ev="slowed",
        dur=3,
        chance=80,
        sec=("vulnerable", 60, 3),
        cd=4,
        mp=20,
    ),
    C(
        id="mob_raizes_fundas",
        name="Raízes Fundas",
        papel="tank",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="buff",
        desc="Se ancora no chão e passa a aguentar o que antes o derrubava.",
        ev=35,
        stat="hp",
        dur=4,
        cd=5,
        mp=22,
    ),
    C(
        id="mob_pisao",
        name="Pisão",
        papel="tank",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Levanta a pata e deixa a massa fazer o trabalho.",
        esc="df.6+st.4",
        bud=140,
        cond="target_wounded",
        bonus=30,
        sec=("stun", 20, 1),
        acc=-15,
        cd=4,
        mp=22,
    ),
    # glass_cannon (+4) — dano alto, nenhuma rede embaixo.
    C(
        id="mob_lanca_de_ozonio",
        name="Lança de Ozônio",
        papel="glass_cannon",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="O ar racha antes do golpe chegar, e o cheiro fica.",
        esc="mg",
        bud=195,
        cond="target_healthy",
        bonus=25,
        sec=("fear", 40, 2),
        cd=3,
        mp=28,
    ),
    C(
        id="mob_sobrecarga",
        name="Sobrecarga",
        papel="glass_cannon",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="buff",
        desc="Abre todas as comportas de uma vez e lida com as consequências depois.",
        ev=45,
        stat="mg",
        dur=3,
        cd=5,
        mp=30,
    ),
    C(
        id="mob_praga_ardente",
        name="Praga Ardente",
        papel="glass_cannon",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Uma chama que não precisa de combustível e não tem pressa.",
        ev="poison",
        dur=5,
        chance=75,
        cd=4,
        mp=24,
    ),
    C(
        id="mob_fenda_de_eter",
        name="Fenda de Éter",
        papel="glass_cannon",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Abre um talho no ar e cobra a conta da própria reserva.",
        esc="mp",
        bud=225,
        cond="target_afflicted",
        bonus=35,
        acc=-10,
        cd=4,
        mp=35,
    ),
]

# --- Lote B: skirmisher, controller, support, elite, boss (17) -------------

LOTE_B = [
    # skirmisher (+3) — Agilidade, mira e esquiva. Difícil de acertar, difícil de ignorar.
    C(
        id="mob_finta",
        name="Finta",
        papel="skirmisher",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Mostra um lado, entra pelo outro.",
        esc="ag",
        bud=140,
        cond="target_healthy",
        bonus=20,
        sec=("slowed", 45, 2),
        acc=15,
        cd=2,
        mp=14,
    ),
    C(
        id="mob_bote",
        name="Bote",
        papel="skirmisher",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Fica parado tempo demais e depois atravessa a distância inteira num salto.",
        esc="ag",
        bud=160,
        cond="target_wounded",
        bonus=30,
        cd=3,
        mp=18,
    ),
    C(
        id="mob_rasteira",
        name="Rasteira",
        papel="skirmisher",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Tira o chão de quem estava confiante nele.",
        ev="stun",
        dur=1,
        chance=45,
        cd=4,
        mp=20,
    ),
    # controller (+4) — nega turno e nega recurso. É contra ele que se guarda a poção.
    C(
        id="mob_teia_de_gelo",
        name="Teia de Gelo",
        papel="controller",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="O chão vira vidro e as pernas param de responder.",
        ev="frozen",
        dur=2,
        chance=60,
        cd=4,
        mp=26,
    ),
    C(
        id="mob_letargia",
        name="Letargia",
        papel="controller",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Uma nota grave e longa que faz as pálpebras pesarem.",
        ev="sleep",
        dur=3,
        chance=55,
        cd=5,
        mp=28,
    ),
    C(
        id="mob_ferrugem_da_alma",
        name="Ferrugem da Alma",
        papel="controller",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Corrói a guarda antes de corroer o corpo.",
        ev="vulnerable",
        dur=3,
        chance=75,
        sec=("weakened", 60, 3),
        cd=4,
        mp=22,
    ),
    C(
        id="mob_agulhada_mental",
        name="Agulhada Mental",
        papel="controller",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage",
        desc="Pouco estrago, e exatamente em quem não podia perder a concentração.",
        esc="mg",
        bud=130,
        cond="target_afflicted",
        bonus=35,
        sec=("mana_burn", 50, 2),
        acc=10,
        cd=3,
        mp=20,
    ),
    # support (+4) — não mata. Faz o resto do grupo demorar mais para morrer.
    C(
        id="mob_canto_de_ossos",
        name="Canto de Ossos",
        papel="support",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="buff",
        desc="Uma reza rouca que endurece o braço de quem ainda está de pé.",
        ev=35,
        stat="st",
        dur=4,
        cd=5,
        mp=22,
    ),
    C(
        id="mob_veu_protetor",
        name="Véu Protetor",
        papel="support",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="damage_reduction",
        desc="Um tecido fino de nada que segura muita coisa.",
        ev=30,
        dur=3,
        cd=5,
        mp=24,
    ),
    C(
        id="mob_praga_lenta",
        name="Praga Lenta",
        papel="support",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="status",
        desc="Não é para matar. É para o outro chegar cansado no fim.",
        ev="poison",
        dur=5,
        chance=70,
        sec=("frailty", 55, 3),
        cd=4,
        mp=22,
    ),
    C(
        id="mob_folego_emprestado",
        name="Fôlego Emprestado",
        papel="support",
        cls="Monster",
        rar="Common",
        lvl=1,
        tipo="buff",
        desc="Tira de si e dá a quem ainda vai lutar.",
        ev=30,
        stat="hp",
        dur=4,
        cd=5,
        mp=25,
    ),
    # elite (+3) — o mesmo repertório, mais bem executado.
    C(
        id="mob_golpe_de_arauto",
        name="Golpe de Arauto",
        papel="elite",
        cls="Monster",
        rar="Rare",
        lvl=1,
        tipo="damage",
        desc="Um golpe treinado, com o peso do escudo atrás dele.",
        esc="st.7+df.3",
        bud=185,
        cond="target_healthy",
        bonus=25,
        sec=("vulnerable", 55, 3),
        acc=-5,
        cd=3,
        mp=26,
    ),
    C(
        id="mob_grito_de_comando",
        name="Grito de Comando",
        papel="elite",
        cls="Monster",
        rar="Rare",
        lvl=1,
        tipo="buff",
        desc="Não é raiva: é ordem. E o corpo obedece a ordens melhor do que a raiva.",
        ev=25,
        stat="crit_chance",
        dur=4,
        cd=5,
        mp=24,
    ),
    C(
        id="mob_lamina_negra",
        name="Lâmina Negra",
        papel="elite",
        cls="Monster",
        rar="Rare",
        lvl=1,
        tipo="damage",
        desc="A lâmina foi tratada com alguma coisa, e a ferida não fecha.",
        esc="st",
        bud=175,
        cond="target_wounded",
        bonus=30,
        sec=("bleed", 70, 3),
        cd=3,
        mp=24,
    ),
    # boss (+3) — o repertório completo, e uma segunda metade de luta.
    C(
        id="boss_juizo",
        name="Juízo",
        papel="boss",
        cls="Monster",
        rar="Epic",
        lvl=1,
        tipo="damage",
        desc="Quando a fera entende que pode perder, ela para de se conter.",
        esc="st.6+hp.4",
        bud=230,
        cond="caster_wounded",
        bonus=45,
        acc=-10,
        cd=4,
        mp=32,
    ),
    C(
        id="boss_sentenca",
        name="Sentença",
        papel="boss",
        cls="Monster",
        rar="Epic",
        lvl=1,
        tipo="status",
        desc="Diz alguma coisa numa língua morta, e o herói entende assim mesmo.",
        ev="fear",
        dur=4,
        chance=85,
        sec=("vulnerable", 70, 3),
        cd=5,
        mp=30,
    ),
    C(
        id="boss_carne_antiga",
        name="Carne Antiga",
        papel="boss",
        cls="Monster",
        rar="Epic",
        lvl=1,
        tipo="heal",
        desc="O corpo se lembra de como era antes do ferimento. Recupera 20% da vida máxima.",
        ev=20,
        dur=0,
        cd=6,
        mp=35,
    ),
]

CARTAS = LOTE_A + LOTE_B
