"""Lote Neutral: 30 cartas, o pool que as três classes veem.

Neutral é ferramenta, não classe. O teto ofensivo dela é menor de propósito
(250 contra 400), então uma carta universal nunca é a melhor opção de dano de
ninguém — o que ela oferece é o que a classe do jogador NÃO tem: defesa,
precisão, sustento moderado, controle leve e pivôs de equipamento.

Por isso a maioria destas cartas não causa dano nenhum, e as poucas que causam
ficam bem abaixo do que a classe do jogador já entrega.
"""

from skill_forge import Carta as C  # noqa: N817 — `C` mantém 150 cartas legíveis

N = "Neutral"

CARTAS = [
    # ---------------- Common (15) ----------------
    C(
        id="n_guarda_alta",
        name="Guarda Alta",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="A primeira coisa que se aprende em qualquer escola de armas.",
        ev=25,
        stat="df",
        dur=3,
        cd=2,
        mp=5.5,
    ),
    C(
        id="n_respirar_fundo",
        name="Respirar Fundo",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="heal",
        desc="Um instante para si mesmo no meio do barulho. Recupera 10% da vida máxima.",
        ev=10,
        dur=0,
        cd=4,
        mp=7.0,
    ),
    C(
        id="n_mira_calma",
        name="Mira Calma",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Sem pressa, sem floreio, no lugar onde vai doer.",
        esc="df",
        bud=218,
        cond="target_healthy",
        bonus=15,
        acc=15,
        sec=("vulnerable", 40, 2),
        cd=2,
        mp=5.0,
    ),
    C(
        id="n_passo_lateral",
        name="Passo Lateral",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Sai da linha do golpe em vez de aparar.",
        ev=22,
        stat="evasion",
        dur=3,
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_pausa_util",
        name="Pausa Útil",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Para de gastar por um momento e deixa o corpo repor.",
        ev=14,
        stat="mana_regen",
        dur=4,
        cd=3,
        mp=4.5,
    ),
    C(
        id="n_grito_curto",
        name="Grito Curto",
        cls=N,
        rar="Common",
        lvl=3,
        tipo="status",
        desc="Não intimida ninguém por muito tempo. Só o suficiente.",
        ev="fear",
        dur=2,
        chance=70,
        sec=("weakened", 40, 2),
        cd=3,
        mp=5.5,
    ),
    C(
        id="n_areia_no_chao",
        name="Areia no Chão",
        cls=N,
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Espalha o que estiver solto no piso e o inimigo passa a medir cada passo.",
        ev="slowed",
        dur=3,
        chance=75,
        sec=("vulnerable", 45, 3),
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_couro_batido",
        name="Couro Batido",
        cls=N,
        rar="Common",
        lvl=6,
        tipo="damage_reduction",
        desc="Equipamento remendado no acampamento, e ainda assim equipamento.",
        ev=20,
        dur=2,
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_estocada_seca",
        name="Estocada Seca",
        cls=N,
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Um movimento só, do ombro ao punho. O que ele abre não fecha sozinho.",
        ev="bleed",
        dur=3,
        chance=70,
        req={"hand_type": "sword"},
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_travar_o_pulso",
        name="Travar o Pulso",
        cls=N,
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Prende a mão que segura a arma o bastante para o turno se perder.",
        ev="weakened",
        dur=3,
        chance=75,
        sec=("slowed", 45, 3),
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_folego_de_marcha",
        name="Fôlego de Marcha",
        cls=N,
        rar="Common",
        lvl=6,
        tipo="buff",
        desc="O corpo de quem andou muito aguenta mais um pouco.",
        ev=25,
        stat="hp",
        dur=4,
        cd=4,
        mp=7.0,
    ),
    C(
        id="n_olho_treinado",
        name="Olho Treinado",
        cls=N,
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="Sabe onde a armadura de cada povo é mais fina.",
        ev=12,
        stat="crit_chance",
        dur=3,
        req={"hand_type": "bow"},
        cd=3,
        mp=6.5,
    ),
    C(
        id="n_pancada_na_nuca",
        name="Pancada na Nuca",
        cls=N,
        rar="Common",
        lvl=9,
        tipo="status",
        desc="Não derruba ninguém. Só faz o outro perder o fio do que estava fazendo.",
        ev="hexed",
        dur=3,
        chance=75,
        cd=3,
        mp=6.0,
    ),
    C(
        id="n_curativo_de_campo",
        name="Curativo de Campo",
        cls=N,
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="Enfaixa o que dá para enfaixar e segue.",
        ev=15,
        stat="life_steal",
        dur=3,
        cd=4,
        mp=7.5,
    ),
    C(
        id="n_encarar",
        name="Encarar",
        cls=N,
        rar="Common",
        lvl=9,
        tipo="status",
        desc="Olha nos olhos e não pisca. Alguma coisa no outro cede.",
        ev="vulnerable",
        dur=3,
        chance=70,
        sec=("fear", 40, 2),
        cd=3,
        mp=6.5,
    ),
    # ---------------- Rare (9) ----------------
    C(
        id="n_disciplina_de_forja",
        name="Disciplina de Forja",
        cls=N,
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Nem toda escola de armas ensina a bater. Algumas ensinam a durar.",
        ev=40,
        stat="df",
        dur=4,
        req={"two_weapons": True},
        cd=4,
        mp=9.0,
    ),
    C(
        id="n_guarda_cruzada",
        name="Guarda Cruzada",
        cls=N,
        rar="Rare",
        lvl=9,
        tipo="damage_reduction",
        desc="As duas armas em X na frente do peito. Não sobra mão para revidar.",
        ev=32,
        dur=3,
        req={"two_weapons": True},
        cd=4,
        mp=9.5,
    ),
    C(
        id="n_ritmo_de_duelo",
        name="Ritmo de Duelo",
        cls=N,
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Encontra o compasso do adversário e passa a chegar meio tempo antes.",
        ev=35,
        stat="ag",
        dur=3,
        cd=4,
        mp=9.0,
    ),
    C(
        id="n_leitura_de_terreno",
        name="Leitura de Terreno",
        cls=N,
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Escolhe onde pisar antes de precisar pisar.",
        ev=38,
        stat="evasion",
        dur=3,
        req={"hand_type": "dagger"},
        cd=4,
        mp=9.5,
    ),
    C(
        id="n_marca_do_cacador",
        name="Marca do Caçador",
        cls=N,
        rar="Rare",
        lvl=12,
        tipo="damage",
        desc="Deixa um sinal no alvo que a mão encontra sozinha depois.",
        esc="df.5+ag.5",
        bud=267,
        cond="target_afflicted",
        bonus=25,
        sec=("bleed", 60, 3),
        req={"hand_type": "bow"},
        cd=4,
        mp=9.5,
    ),
    C(
        id="n_voto_de_silencio",
        name="Voto de Silêncio",
        cls=N,
        rar="Rare",
        lvl=12,
        tipo="status",
        desc="Nenhuma palavra sai da boca do outro, e o que ele ia conjurar fica lá dentro.",
        ev="mana_burn",
        dur=2,
        chance=80,
        sec=("hexed", 60, 3),
        cd=4,
        mp=9.0,
    ),
    C(
        id="n_amuleto_rachado",
        name="Amuleto Rachado",
        cls=N,
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Quebrou defendendo alguém. Ainda tem uma última carga.",
        ev=35,
        stat="mp",
        dur=4,
        cd=5,
        mp=6.0,
    ),
    C(
        id="n_gancho_e_corda",
        name="Gancho e Corda",
        cls=N,
        rar="Rare",
        lvl=12,
        tipo="status",
        desc="Não é uma arma. É um jeito de decidir onde o inimigo vai estar.",
        ev="stun",
        dur=1,
        chance=50,
        sec=("vulnerable", 60, 3),
        cd=4,
        mp=10.0,
    ),
    C(
        id="n_lamina_assentada",
        name="Lâmina Assentada",
        cls=N,
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Passa a pedra na lâmina até o fio decidir sozinho onde entra.",
        ev=35,
        stat="crit_damage",
        dur=3,
        req={"hand_type": "sword"},
        cd=4,
        mp=9.0,
    ),
    # ---------------- Epic (6) ----------------
    C(
        id="n_postura_impecavel",
        name="Postura Impecável",
        cls=N,
        rar="Epic",
        lvl=12,
        tipo="buff",
        desc="Vinte anos de repetição até a técnica pesar mais que o músculo.",
        ev=55,
        stat="st",
        dur=4,
        cd=5,
        mp=12.5,
    ),
    C(
        id="n_mao_que_nao_treme",
        name="A Mão que Não Treme",
        cls=N,
        rar="Epic",
        lvl=15,
        tipo="buff",
        desc="Não é coragem. É ter feito isto vezes demais para a mão ainda perguntar.",
        ev=60,
        stat="crit_damage",
        dur=4,
        req={"hand_type": "mace"},
        cd=5,
        mp=12.5,
    ),
    C(
        id="n_ultima_carta",
        name="Última Carta",
        cls=N,
        rar="Epic",
        lvl=15,
        tipo="damage",
        desc="Guardada para o momento em que o resto já falhou.",
        esc="hp",
        bud=239,
        cond="caster_wounded",
        bonus=50,
        acc=-10,
        sec=("fear", 55, 3),
        cd=5,
        mp=12.0,
    ),
    C(
        id="n_pacto_de_ferro",
        name="Pacto de Ferro",
        cls=N,
        rar="Epic",
        lvl=15,
        tipo="damage_reduction",
        desc="Um acordo antigo entre o corpo e o metal: nenhum dos dois cede primeiro.",
        ev=45,
        dur=4,
        req={"hand_type": "mace"},
        cd=5,
        mp=13.0,
    ),
    C(
        id="n_hora_do_arauto",
        name="Hora do Arauto",
        cls=N,
        rar="Epic",
        lvl=12,
        tipo="status",
        desc="Anuncia o que vai acontecer, e o inimigo acredita antes de ver.",
        ev="fear",
        dur=4,
        chance=85,
        sec=("vulnerable", 70, 3),
        cd=5,
        mp=12.0,
    ),
    C(
        id="n_paciencia_do_coveiro",
        name="Paciência do Coveiro",
        cls=N,
        rar="Epic",
        lvl=15,
        tipo="status",
        desc="Ele não tem pressa. O trabalho dele sempre acaba chegando.",
        ev="poison",
        dur=5,
        chance=85,
        sec=("frailty", 70, 4),
        cd=5,
        mp=12.0,
    ),
]
