"""Lote Rogue: 26 cartas novas, para fechar 40.

Identidade: Agilidade, precisão e evasão, oportunismo, dano por turno, golpes
rápidos, e controle sobre chance e momento. O Ladino não decide se acerta forte:
decide QUANDO acerta, e é por isso que as condições situacionais e a mira são a
moeda dele.
"""

from skill_forge import Carta as C  # noqa: N817 — `C` mantém 150 cartas legíveis

CARTAS = [
    # ---------------- Common (13) ----------------
    C(
        id="corte_de_tendao",
        name="Corte de Tendão",
        cls="Rogue",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Não busca o coração. Busca o que segura o inimigo de pé.",
        esc="ag",
        bud=195,
        cond="target_healthy",
        bonus=12,
        sec=("slowed", 55, 3),
        cd=2,
        mp=5.5,
    ),
    C(
        id="picada_certeira",
        name="Picada Certeira",
        cls="Rogue",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Uma estocada curta que nunca erra o lugar.",
        esc="ag",
        bud=159,
        cond="target_afflicted",
        bonus=15,
        acc=15,
        req={"hand_type": "dagger"},
        sec=("bleed", 40, 2),
        cd=1,
        mp=4.5,
    ),
    C(
        id="flecha_pela_fresta",
        name="Flecha pela Fresta",
        cls="Rogue",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Espera o inimigo abrir a guarda e paga a espera à distância.",
        esc="ag",
        bud=175,
        cond="target_afflicted",
        bonus=25,
        acc=10,
        req={"hand_type": "bow"},
        sec=("slowed", 50, 3),
        cd=2,
        mp=6.5,
    ),
    C(
        id="dose_da_viuva",
        name="Dose da Viúva",
        cls="Rogue",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="A lâmina passa raspando; o que ela deixou é que resolve.",
        esc="ag",
        bud=166,
        cond="target_wounded",
        bonus=20,
        sec=("poison", 60, 5),
        req={"hand_type": "dagger"},
        cd=2,
        mp=6.5,
    ),
    C(
        id="faro_de_rua",
        name="Faro de Rua",
        cls="Rogue",
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Sabe em que beco descansar e em que hora sair dele.",
        ev=12,
        stat="mana_regen",
        dur=4,
        cd=3,
        mp=5.0,
    ),
    C(
        id="respiracao_de_ladrao",
        name="Respiração de Ladrão",
        cls="Rogue",
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Conta os batimentos até a mão parar de tremer.",
        ev=15,
        stat="crit_chance",
        dur=3,
        cd=3,
        mp=6.0,
    ),
    C(
        id="capa_rasgada",
        name="Capa Rasgada",
        cls="Rogue",
        rar="Common",
        lvl=3,
        tipo="damage_reduction",
        desc="Enrola a capa no braço e aceita perder o tecido em vez do osso.",
        ev=20,
        dur=2,
        cd=3,
        mp=6.0,
    ),
    C(
        id="pó_nos_olhos",
        name="Pó nos Olhos",
        cls="Rogue",
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Punhado de cinza, mão rápida, e o inimigo passa a chutar o escuro.",
        ev="fear",
        dur=3,
        chance=75,
        sec=("slowed", 45, 2),
        cd=3,
        mp=6.0,
    ),
    C(
        id="joelho_torto",
        name="Joelho Torto",
        cls="Rogue",
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Um pontapé na articulação. Nada elegante, muito eficaz.",
        ev="slowed",
        dur=3,
        chance=80,
        sec=("bleed", 35, 2),
        cd=3,
        mp=6.5,
    ),
    C(
        id="leitura_de_guarda",
        name="Leitura de Guarda",
        cls="Rogue",
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="Assiste três trocas de golpe sem revidar, e depois não erra mais.",
        ev=30,
        stat="crit_damage",
        dur=3,
        req={"hand_type": "dagger"},
        cd=3,
        mp=7.5,
    ),
    C(
        id="bolso_furado",
        name="Bolso Furado",
        cls="Rogue",
        rar="Common",
        lvl=9,
        tipo="status",
        desc="Corta a bolsa de componentes antes de cortar o dono.",
        ev="mana_burn",
        dur=2,
        chance=75,
        sec=("clouded", 60, 3),
        cd=3,
        mp=6.0,
    ),
    C(
        id="duas_maos_um_tempo",
        name="Duas Mãos, Um Tempo",
        cls="Rogue",
        rar="Common",
        lvl=9,
        tipo="damage",
        desc="Os dois braços saem juntos e chegam em momentos diferentes.",
        esc="ag",
        bud=185,
        cond="target_healthy",
        bonus=18,
        req={"two_weapons": True},
        sec=("bleed", 50, 3),
        cd=2,
        mp=7.5,
    ),
    C(
        id="ferida_paga",
        name="Ferida Paga",
        cls="Rogue",
        rar="Common",
        lvl=9,
        tipo="heal",
        desc="Costura o corte com o que sobrou do kit. Recupera 10% da vida máxima.",
        ev=10,
        dur=0,
        cd=4,
        mp=7.0,
    ),
    # ---------------- Rare (8) ----------------
    C(
        id="lamina_no_escuro",
        name="Lâmina no Escuro",
        cls="Rogue",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="O inimigo nunca vê de onde veio, e nem devia.",
        esc="ag",
        bud=230,
        cond="target_wounded",
        bonus=35,
        acc=15,
        req={"hand_type": "dagger"},
        sec=("vulnerable", 60, 3),
        cd=3,
        mp=9.5,
    ),
    C(
        id="marcar_a_presa",
        name="Marcar a Presa",
        cls="Rogue",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="Escolhe onde vai doer e passa o resto do combate voltando ali.",
        esc="ag",
        bud=215,
        cond="target_healthy",
        bonus=28,
        sec=("vulnerable", 65, 3),
        cd=3,
        mp=9.0,
    ),
    C(
        id="chuva_de_ferrões",
        name="Chuva de Ferrões",
        cls="Rogue",
        rar="Rare",
        lvl=12,
        tipo="damage",
        desc="Seis agulhas ao mesmo tempo, e nenhuma delas era a importante.",
        esc="ag",
        bud=220,
        cond="target_afflicted",
        bonus=30,
        sec=("bleed", 70, 3),
        req={"hand_type": "bow"},
        cd=3,
        mp=9.5,
    ),
    C(
        id="bolso_do_alfaiate",
        name="Bolso do Alfaiate",
        cls="Rogue",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Sempre há mais um bolso, e nele sempre há mais um truque.",
        ev=40,
        stat="mp",
        dur=4,
        cd=5,
        mp=6.5,
    ),
    C(
        id="sangria_lenta",
        name="Sangria Lenta",
        cls="Rogue",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Cada corte que ele abre, ele fecha um seu.",
        ev=22,
        stat="life_steal",
        dur=3,
        req={"hand_type": "dagger"},
        cd=4,
        mp=10.0,
    ),
    C(
        id="olho_do_falcão",
        name="Olho do Falcão",
        cls="Rogue",
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Enxerga a costura da armadura a trinta passos.",
        ev=40,
        stat="crit_damage",
        dur=3,
        req={"hand_type": "bow"},
        cd=4,
        mp=9.5,
    ),
    C(
        id="nó_corredio",
        name="Nó Corredio",
        cls="Rogue",
        rar="Rare",
        lvl=12,
        tipo="status",
        desc="Um laço no tornozelo e o combate passa a ser onde ele quiser.",
        ev="stun",
        dur=1,
        chance=55,
        sec=("slowed", 65, 3),
        cd=4,
        mp=10.5,
    ),
    C(
        id="couro_endurecido",
        name="Couro Endurecido",
        cls="Rogue",
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Placas costuradas por dentro do casaco, onde ninguém procura.",
        ev=40,
        stat="df",
        dur=3,
        cd=4,
        mp=9.0,
    ),
    # ---------------- Epic (5) ----------------
    C(
        id="hora_do_lobo",
        name="Hora do Lobo",
        cls="Rogue",
        rar="Epic",
        lvl=12,
        tipo="damage",
        desc="A hora entre a última ronda e o primeiro galo. Ninguém está pronto.",
        esc="ag",
        bud=300,
        cond="target_healthy",
        bonus=40,
        acc=15,
        req={"hand_type": "dagger"},
        sec=("bleed", 65, 3),
        cd=4,
        mp=13.0,
    ),
    C(
        id="cobranca_de_juros",
        name="Cobrança de Juros",
        cls="Rogue",
        rar="Epic",
        lvl=18,
        tipo="damage",
        desc="Cada veneno, cada corte e cada osso torto entram na conta de uma vez.",
        esc="ag",
        bud=325,
        cond="target_afflicted",
        bonus=45,
        sec=("bleed", 80, 3),
        cd=4,
        mp=14.0,
    ),
    C(
        id="testamento_do_ladrao",
        name="Testamento do Ladrão",
        cls="Rogue",
        rar="Epic",
        lvl=15,
        tipo="damage",
        desc="Com uma mão na ferida e a outra na adaga, ele não guarda mais nada.",
        esc="ag.6+hp.4",
        bud=300,
        cond="caster_wounded",
        bonus=50,
        sec=("poison", 70, 4),
        req={"two_weapons": True},
        cd=4,
        mp=13.5,
    ),
    C(
        id="silencio_de_seda",
        name="Silêncio de Seda",
        cls="Rogue",
        rar="Epic",
        lvl=15,
        tipo="status",
        desc="Fecha a boca do conjurador com um pano e uma promessa.",
        ev="sleep",
        dur=3,
        chance=60,
        sec=("mana_burn", 70, 2),
        cd=5,
        mp=13.0,
    ),
    C(
        id="mao_leve",
        name="Mão Leve",
        cls="Rogue",
        rar="Epic",
        lvl=12,
        tipo="buff",
        desc="As duas lâminas passam a encontrar sozinhas o lugar entre as costelas.",
        ev=35,
        stat="crit_chance",
        dur=4,
        req={"two_weapons": True},
        cd=5,
        mp=13.0,
    ),
]
