"""Lote Warrior: 27 cartas novas, para fechar 40.

Identidade: Força, resistência, atrito, controle de corpo a corpo, e a Defesa
podendo virar poder. O Guerreiro não ganha por pico — ganha por continuar de pé
enquanto o outro não continua. As cartas abaixo tentam dar formas diferentes de
fazer isso, e não quinze maneiras de bater mais forte.
"""

from skill_forge import Carta as C  # noqa: N817 — `C` mantém 150 cartas legíveis

CARTAS = [
    # ---------------- Common (13) ----------------
    C(
        id="quebra_guarda",
        name="Quebra-Guarda",
        cls="Warrior",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Um golpe que busca a brecha entre a arma e o corpo, e abre o alvo para o próximo.",
        esc="st",
        bud=185,
        cond="target_healthy",
        bonus=12,
        sec=("vulnerable", 45, 3),
        req={"hand_type": "sword"},
        cd=2,
        mp=5.5,
    ),
    C(
        id="pisada_de_ferro",
        name="Pisada de Ferro",
        cls="Warrior",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Todo o peso da armadura descendo sobre quem não tem como sair do caminho.",
        esc="st",
        bud=180,
        cond="target_afflicted",
        bonus=25,
        acc=-5,
        sec=("slowed", 50, 3),
        cd=2,
        mp=7.5,
    ),
    C(
        id="berro_de_ferro",
        name="Berro de Ferro",
        cls="Warrior",
        rar="Common",
        lvl=3,
        tipo="status",
        desc="Um berro que estilhaça a concentração de quem estava recitando algo.",
        ev="hexed",
        dur=3,
        chance=70,
        sec=("fear", 45, 2),
        cd=2,
        mp=5.0,
    ),
    C(
        id="postura_de_muro",
        name="Postura de Muro",
        cls="Warrior",
        rar="Common",
        lvl=3,
        tipo="buff",
        desc="Planta os pés, a espada na diagonal, e fecha a linha inteira.",
        ev=30,
        stat="df",
        dur=3,
        req={"hand_type": "sword"},
        cd=2,
        mp=6.5,
    ),
    C(
        id="couraca_improvisada",
        name="Couraça Improvisada",
        cls="Warrior",
        rar="Common",
        lvl=3,
        tipo="damage_reduction",
        desc="Amarra o que sobrou do escudo no braço e aguenta o próximo golpe.",
        ev=20,
        dur=2,
        cd=3,
        mp=6.0,
    ),
    C(
        id="soco_de_placa",
        name="Soco de Placa",
        cls="Warrior",
        rar="Common",
        lvl=3,
        tipo="damage",
        desc="Sem arma, sem espaço, sem elegância: a manopla resolve.",
        esc="st",
        bud=165,
        cond="caster_wounded",
        bonus=20,
        sec=("weakened", 35, 2),
        cd=1,
        mp=4.0,
    ),
    C(
        id="marca_do_acougueiro",
        name="Marca do Açougueiro",
        cls="Warrior",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Um corte que não fecha sozinho.",
        esc="st",
        bud=167,
        cond="target_wounded",
        bonus=22,
        sec=("bleed", 55, 3),
        req={"hand_type": "axe"},
        cd=2,
        mp=7.0,
    ),
    C(
        id="investida_de_ariete",
        name="Investida de Aríete",
        cls="Warrior",
        rar="Common",
        lvl=6,
        tipo="damage",
        desc="Ombro na linha do peito, à velocidade que a armadura permitir.",
        esc="st",
        bud=170,
        cond="target_healthy",
        bonus=15,
        req={"hand_type": "sword"},
        sec=("stun", 20, 1),
        cd=2,
        mp=6.5,
    ),
    C(
        id="olho_de_ferreiro",
        name="Olho de Ferreiro",
        cls="Warrior",
        rar="Common",
        lvl=6,
        tipo="buff",
        desc="Aprende onde a placa do inimigo é mais fina.",
        ev=14,
        stat="crit_chance",
        dur=3,
        cd=3,
        mp=6.0,
    ),
    C(
        id="fio_no_rebite",
        name="Fio no Rebite",
        cls="Warrior",
        rar="Common",
        lvl=9,
        tipo="buff",
        desc="Assenta a lâmina para que o golpe certo valha por dois.",
        ev=25,
        stat="crit_damage",
        dur=3,
        req={"hand_type": "sword"},
        cd=3,
        mp=7.0,
    ),
    C(
        id="sangue_nos_olhos",
        name="Sangue nos Olhos",
        cls="Warrior",
        rar="Common",
        lvl=6,
        tipo="status",
        desc="Um talho na testa: o inimigo passa a se defender com um olho só.",
        ev="vulnerable",
        dur=3,
        chance=70,
        sec=("bleed", 45, 2),
        cd=3,
        mp=6.0,
    ),
    C(
        id="tomar_folego",
        name="Tomar Fôlego",
        cls="Warrior",
        rar="Common",
        lvl=9,
        tipo="heal",
        desc="Recua um passo, respira, e volta. Recupera 12% da vida máxima.",
        ev=12,
        dur=0,
        cd=4,
        mp=8.0,
    ),
    C(
        id="peso_do_machado",
        name="Peso do Machado",
        cls="Warrior",
        rar="Common",
        lvl=9,
        tipo="damage",
        desc="Não é técnica, é gravidade: o machado cai onde a força mandou.",
        esc="st",
        bud=190,
        cond="target_afflicted",
        bonus=20,
        acc=-10,
        req={"hand_type": "axe"},
        sec=("vulnerable", 55, 3),
        cd=2,
        mp=7.5,
    ),
    # ---------------- Rare (9) ----------------
    C(
        id="baluarte",
        name="Baluarte",
        cls="Warrior",
        rar="Rare",
        lvl=6,
        tipo="damage_reduction",
        desc="Planta a maça no chão e faz do próprio corpo o portão.",
        ev=32,
        dur=3,
        req={"hand_type": "mace"},
        cd=4,
        mp=9.0,
    ),
    C(
        id="ferro_contra_ferro",
        name="Ferro Contra Ferro",
        cls="Warrior",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="Aparar e devolver no mesmo movimento: a guarda vira o golpe.",
        esc="df.6+st.4",
        bud=215,
        cond="caster_wounded",
        bonus=30,
        sec=("weakened", 60, 3),
        cd=3,
        mp=9.5,
    ),
    C(
        id="rasgo_de_gancho",
        name="Rasgo de Gancho",
        cls="Warrior",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="Puxa o inimigo pela armadura e abre o que estiver embaixo.",
        esc="st",
        bud=210,
        cond="target_healthy",
        bonus=25,
        sec=("bleed", 65, 3),
        req={"hand_type": "axe"},
        cd=3,
        mp=9.0,
    ),
    C(
        id="tremor_de_bigorna",
        name="Tremor de Bigorna",
        cls="Warrior",
        rar="Rare",
        lvl=9,
        tipo="damage",
        desc="A maça encontra o chão e o chão devolve o recado.",
        esc="st.8+df.2",
        bud=205,
        cond="target_afflicted",
        bonus=28,
        sec=("stun", 25, 1),
        acc=-10,
        req={"hand_type": "mace"},
        cd=4,
        mp=10.0,
    ),
    C(
        id="veterania",
        name="Veterania",
        cls="Warrior",
        rar="Rare",
        lvl=9,
        tipo="buff",
        desc="Vinte anos de campanha ensinam onde o golpe vai antes de ele sair.",
        ev=35,
        stat="evasion",
        dur=3,
        req={"hand_type": "sword"},
        cd=4,
        mp=9.5,
    ),
    C(
        id="sede_de_batalha",
        name="Sede de Batalha",
        cls="Warrior",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Cada corte aberto no outro fecha um seu.",
        ev=18,
        stat="life_steal",
        dur=3,
        req={"hand_type": "axe"},
        cd=4,
        mp=10.0,
    ),
    C(
        id="quebra_ossos",
        name="Quebra-Ossos",
        cls="Warrior",
        rar="Rare",
        lvl=12,
        tipo="status",
        desc="Um golpe seco no joelho. O inimigo continua vivo, e mais devagar.",
        ev="slowed",
        dur=3,
        chance=75,
        sec=("bleed", 40, 2),
        cd=3,
        mp=8.5,
    ),
    C(
        id="mao_dupla",
        name="Mão Dupla",
        cls="Warrior",
        rar="Rare",
        lvl=12,
        tipo="damage",
        desc="Duas armas, dois tempos, nenhuma pausa entre eles.",
        esc="st",
        bud=230,
        cond="target_wounded",
        bonus=25,
        req={"two_weapons": True},
        sec=("bleed", 55, 3),
        cd=3,
        mp=10.5,
    ),
    C(
        id="respiracao_de_forja",
        name="Respiração de Forja",
        cls="Warrior",
        rar="Rare",
        lvl=12,
        tipo="buff",
        desc="Controla o fôlego como quem controla o fole: o corpo aguenta mais.",
        ev=30,
        stat="hp",
        dur=4,
        cd=5,
        mp=11.0,
    ),
    # ---------------- Epic (4) ----------------
    C(
        id="juramento_da_muralha",
        name="Juramento da Muralha",
        cls="Warrior",
        rar="Epic",
        lvl=12,
        tipo="damage_reduction",
        desc="Jura não ceder o terreno, e ocupa as duas mãos cumprindo a promessa.",
        ev=45,
        dur=4,
        req={"two_weapons": True},
        cd=5,
        mp=13.0,
    ),
    C(
        id="colheita_de_ferro",
        name="Colheita de Ferro",
        cls="Warrior",
        rar="Epic",
        lvl=15,
        tipo="damage",
        desc="Uma volta completa com a lâmina na altura da cintura.",
        esc="st",
        bud=280,
        cond="target_afflicted",
        bonus=35,
        sec=("bleed", 70, 3),
        acc=-5,
        req={"two_weapons": True},
        cd=4,
        mp=13.5,
    ),
    C(
        id="carga_do_condenado",
        name="Carga do Condenado",
        cls="Warrior",
        rar="Epic",
        lvl=15,
        tipo="damage",
        desc="Quem já perdeu o combate não tem mais o que economizar.",
        esc="hp",
        bud=290,
        cond="caster_wounded",
        bonus=45,
        acc=-10,
        sec=("fear", 60, 3),
        cd=4,
        mp=14.0,
    ),
    C(
        id="silencio_do_veterano",
        name="Silêncio do Veterano",
        cls="Warrior",
        rar="Epic",
        lvl=15,
        tipo="status",
        desc="Nenhuma palavra, nenhuma ameaça: só a certeza de que o próximo passo é ruim.",
        ev="fear",
        dur=3,
        chance=75,
        sec=("vulnerable", 55, 3),
        cd=4,
        mp=11.5,
    ),
    # ---------------- Legendary (1) ----------------
    C(
        id="fortaleza_viva",
        name="Fortaleza Viva",
        cls="Warrior",
        rar="Legendary",
        lvl=18,
        tipo="damage",
        desc=(
            "O que ele passou a vida aguentando volta de uma vez. "
            "Cada placa de armadura vira massa, e a massa vira o golpe."
        ),
        esc="df.6+st.4",
        bud=420,
        cond="caster_wounded",
        bonus=60,
        sec=("stun", 40, 1),
        acc=-15,
        cd=5,
        mp=20.0,
    ),
]
