const C={DEFENSE_K:100,CRIT_DEFAULT:10,CRIT_ROGUE:25,CRIT_CAP:75,CRIT_DAMAGE:1.5,HIT:85,ESSENCE_MIN:.5,ESSENCE_MAX:3,ESSENCE_MEAN:1.2,ESSENCE_STD:.5,XP_BASE:50,XP_SCALE:20,COIN_BASE:30,COIN_SCALE:10};
const classes={Warrior:{hp:104,mp:30,st:104,ag:5,mg:30,df:30,weights:{st:1.6,mg:.4,ag:0}},Mage:{hp:99,mp:100,st:32,ag:5,mg:100,df:25,weights:{st:.3,mg:1.9,ag:0}},Rogue:{hp:99,mp:50,st:75,ag:15,mg:66,df:20,weights:{st:.8,mg:.4,ag:1.7}}};
const skillData={Warrior:[['Golpe Poderoso',15,60,1],['Investida',20,70,1],['Escudo Protetor',25,8,2],['Grito de Guerra',20,10,2]],Mage:[['Bola de Fogo',25,80,1],['Míssil Mágico',20,65,1],['Drenar Vida',30,25,2],['Escudo Mágico',25,5,2]],Rogue:[['Ataque Furtivo',10,80,1],['Golpe Baixo',15,0,2],['Evasão',20,15,2],['Sombra Rápida',18,12,2]]};
const monsters=[['Rato Espectral','rat.svg',100,25,20,3],['Lâmina Errante','blade.svg',120,32,24,7],['Sombra Rastejante','shadow.svg',150,38,28,10],['Guardião Corrompido','guardian.svg',190,48,36,15],['Colosso Fendido','colossus.svg',260,65,48,20]];
let state={floor:1,essence:1,heroClass:'Warrior',hero:{hp:104,maxHp:104,mp:30,maxMp:30,st:104,ag:5,mg:30,df:30,level:1},enemy:null,cooldowns:{}};
const $=id=>document.getElementById(id); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function gaussian(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function rollEssence(){return Math.max(C.ESSENCE_MIN,Math.min(C.ESSENCE_MAX,C.ESSENCE_MEAN+gaussian()*C.ESSENCE_STD+(Math.min(state.floor*.02,.4))))}
function damage(base,def,crit){let x=crit?C.CRIT_DAMAGE:1;return Math.max(1,Math.floor(base*x*(C.DEFENSE_K/(C.DEFENSE_K+Math.max(0,def)))))}
function avgDamage(e){const w=classes[e===state.heroClass?e:'Warrior'].weights;return Math.floor((state.hero.st*w.st+state.hero.mg*w.mg+state.hero.ag*w.ag)/3)}
function enemyForFloor(){const idx=Math.min(monsters.length-1,Math.floor((state.floor-1)/4));const m=monsters[idx];const scale=1+(state.floor-1)*.2;return{name:m[0],sprite:m[1],maxHp:Math.floor(m[2]*scale),hp:Math.floor(m[2]*scale),st:Math.floor(m[3]*scale),df:Math.floor(m[4]*scale),ag:m[5]+Math.floor(state.floor/3)}}
function render(){const h=state.hero,e=state.enemy;$('floor').textContent=`ANDAR ${state.floor}`;$('essence').textContent=`ESSÊNCIA ${state.essence.toFixed(1)}x`;$('heroName').textContent=state.heroClass;$('heroHp').style.width=`${100*h.hp/h.maxHp}%`;$('heroHpText').textContent=`${h.hp} / ${h.maxHp}`;$('mpText').textContent=`MP ${h.mp} / ${h.maxMp}`;$('enemyName').textContent=e.name;$('enemyHp').style.width=`${100*e.hp/e.maxHp}%`;$('enemyHpText').textContent=`${e.hp} / ${e.maxHp}`;$('enemySprite').style.backgroundImage=`url('./sprites/${e.sprite}')`}
async function animate(attacker,amount,critical=false){const a=attacker==='hero'?$('heroSprite'):$('enemySprite');const d=$('damage');a.classList.remove('attack','hit');void a.offsetWidth;a.classList.add('attack');await sleep(180);if(amount>0){d.textContent=critical?`${amount}!`:`-${amount}`;d.classList.remove('damage-pop');void d.offsetWidth;d.classList.add('damage-pop')}await sleep(220);const target=attacker==='hero'?'enemySprite':'heroSprite';$(target).classList.add('hit');await sleep(180);a.classList.remove('attack');$(target).classList.remove('hit')}
function log(t){$('log').textContent=t}
async function heroAttack(){if(!state.enemy)return;const hit=Math.floor(Math.random()*100)+1<=C.HIT+(state.hero.ag-state.enemy.ag);if(!hit){log('O golpe errou.');await animate('hero',0);return enemyTurn()}const crit=Math.floor(Math.random()*100)+1<=C.CRIT_DEFAULT;const n=damage(avgDamage(state.heroClass),state.enemy.df,crit);state.enemy.hp=Math.max(0,state.enemy.hp-n);await animate('hero',n,crit);log(crit?`CRÍTICO. ${n} de dano.`:`Você causou ${n} de dano.`);if(state.enemy.hp<=0)return victory();return enemyTurn()}
async function enemyTurn(){await sleep(300);if(state.enemy.hp<=0)return;const hit=Math.floor(Math.random()*100)+1<=C.HIT+(state.enemy.ag-state.hero.ag);if(!hit){log('O inimigo errou.');await animate('enemy',0);return}const n=damage(Math.floor((state.enemy.st+state.enemy.st*.2)/3),state.hero.df,false);state.hero.hp=Math.max(0,state.hero.hp-n);await animate('enemy',n);log(`Você recebeu ${n} de dano.`);render();if(state.hero.hp<=0)gameOver()}
function openSkills(){$('skillPanel').classList.remove('hidden');const box=$('skills');box.innerHTML='';skillData[state.heroClass].forEach((s,i)=>{const b=document.createElement('button');b.className='skill';b.innerHTML=`${s[0]}<small>MP ${s[1]} · CD ${s[3]}</small>`;b.onclick=async()=>{if((state.cooldowns[i]||0)>0)return log('Habilidade em recarga.');if(state.hero.mp<s[1])return log('MP insuficiente.');state.hero.mp-=s[1];state.cooldowns[i]=s[3];$('skillPanel').classList.add('hidden');if(s[2]){const crit=s[0]==='Ataque Furtivo'&&Math.floor(Math.random()*100)+1<=C.CRIT_ROGUE;const n=damage(avgDamage(state.heroClass)+Math.floor(s[2]*(1+state.hero.level*.08)),state.enemy.df,crit);state.enemy.hp=Math.max(0,state.enemy.hp-n);await animate('hero',n,crit);log(`${s[0]} causou ${n} de dano.`);if(state.enemy.hp<=0)return victory()}render();enemyTurn()};box.appendChild(b)})}
async function potion(){if(state.hero.hp===state.hero.maxHp)return log('Sua vida já está cheia.');const n=Math.min(30,state.hero.maxHp-state.hero.hp);state.hero.hp+=n;log(`Poção recuperou ${n} HP.`);render();await sleep(500);enemyTurn()}
async function flee(){if(Math.floor(Math.random()*2)===0){log('Você escapou.');await sleep(500);openExtraction()}else{log('A fuga falhou.');enemyTurn()}}
function victory(){const xp=Math.floor((C.XP_BASE+C.XP_SCALE*state.floor)*state.essence);state.hero.level+=xp>=3000?1:0;state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;render();$('resultTitle').textContent='INIMIGO DERROTADO';$('resultBody').innerHTML=`Essência: +${xp}<br>Ouro: +${C.COIN_BASE+C.COIN_SCALE*state.floor}`;$('resultActions').innerHTML='<button id="next">PRÓXIMO ANDAR</button><button id="extract">EXTRAIR AGORA</button>';$('resultPanel').classList.remove('hidden');$('next').onclick=()=>{state.floor++;state.essence=rollEssence();state.enemy=enemyForFloor();$('resultPanel').classList.add('hidden');render();log(`Andar ${state.floor}. O multiplicador foi revelado.`)};$('extract').onclick=()=>{$('resultPanel').classList.add('hidden');openExtraction()}}
function openExtraction(){$('revealMultiplier').textContent=state.essence.toFixed(1)+'x';$('extractPanel').classList.remove('hidden')}
function gameOver(){log('Você morreu. A Forge Run terminou.');$('resultTitle').textContent='MORTE';$('resultBody').textContent='O gladiador foi perdido.';$('resultActions').innerHTML='<button onclick="location.reload()">NOVA RUN</button>';$('resultPanel').classList.remove('hidden')}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({attack:heroAttack,skill:openSkills,potion,flee}[b.dataset.action])());document.querySelector('[data-close]').onclick=()=>$('skillPanel').classList.add('hidden');$('continueBtn').onclick=()=>{$('extractPanel').classList.add('hidden');state.floor++;state.essence=rollEssence();state.enemy=enemyForFloor();render();log(`Você continua. Andar ${state.floor}.`)};$('extractBtn').onclick=()=>{$('extractPanel').classList.add('hidden');log('Run extraída. Progresso preservado.')};
state.enemy=enemyForFloor();render();
